### ISSUE TITLE
can't create project - panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by clarking** [fragmenta/fragmenta-cms#27]
I can't create a new fragmenta project from src folder, when i run the command 
`fragmenta new cms fragmenta ` throws the following error:

```
clarking@falcon65:~/gocode/src$ fragmenta new cms fragmenta
00:21:33 Fetching from url: github.com/fragmenta/fragmenta-cms
00:21:47 Creating files at: /home/clarking/gocode/src/fragmenta
00:21:47 Removing all at:/home/clarking/gocode/src/fragmenta/.git
00:21:47 Initialising new git repo at:/home/clarking/gocode/src/fragmenta
00:21:47 Updating import paths to: fragmenta
00:21:47 Generating new config at /home/clarking/gocode/src/fragmenta/secrets/fragmenta.json
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x6ddd80, 0xc4200101b0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.ToCamel(0x0, 0x0, 0xc4201397da, 0x1)
	/home/clarking/gocode/src/github.com/fragmenta/fragmenta/textual.go:50 +0x28f
main.reifyString(0xc42027f400, 0x937, 0x937, 0xb37)
	/home/clarking/gocode/src/github.com/fragmenta/fragmenta/generate.go:527 +0x1db
main.generateCreateSQL(0xc420017440, 0x23, 0x0, 0x0)
	/home/clarking/gocode/src/github.com/fragmenta/fragmenta/new.go:218 +0x52e
main.RunNew(0xc42000c380, 0x4, 0x4)
	/home/clarking/gocode/src/github.com/fragmenta/fragmenta/new.go:88 +0x5ff
main.main()
	/home/clarking/gocode/src/github.com/fragmenta/fragmenta/fragmenta.go:69 +0x7d4
clarking@falcon65:~/gocode/src$ 

```
i'm on xubuntu 16.04 running go1.7.4 linux/amd64

any help on this issue would be appreciated

**Comment by kennygrant** [comment]
Thanks for reporting. I'm just in the middle of updating the default templates, and should be done this week. I'll try to look into this at the same time.
